stages:
  - build
  - deploy

# global variables
variables: &global-variables
  GIT_STRATEGY: clone
  PYTHON_VER: 3

.setup_esp_idf: &setup_esp_idf
  - cd $IDF_PATH
  - git fetch origin ${idf_branch}
  - git checkout ${idf_branch}
  - git submodule update --init --recursive
  - ./install.sh
  - . ./export.sh
  - cd -

.before_script_preparation: &before_script_preparation
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - export IDF_PATH=/opt/esp/idf

.build_iot_bridge_default: &build_iot_bridge_default
  - cd examples/wireless_nic
  - echo -e "\nCONFIG_BRIDGE_EXTERNAL_NETIF_ETHERNET=y" >> sdkconfig.defaults.${idf_target}
  - idf.py set-target ${idf_target}
  - idf.py build

  - rm -rf build sdkconfig
  - sed -i '$d' sdkconfig.defaults.${idf_target}
  - echo -e "\nCONFIG_BRIDGE_EXTERNAL_NETIF_MODEM=y" >> sdkconfig.defaults.${idf_target}
  - echo -e "\nCONFIG_APP_BRIDGE_USE_WIFI_PROVISIONING_OVER_BLE=y" >> sdkconfig.defaults.${idf_target}
  - echo -e "\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_ETHERNET=y\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_SPI=y" >> sdkconfig.defaults.${idf_target}
  - idf.py set-target ${idf_target}
  - idf.py build

.build_iot_bridge_esp32: &build_iot_bridge_esp32
  - cd examples/wireless_nic
  - echo -e "\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_SDIO=y" >> sdkconfig.defaults.esp32
  - idf.py set-target esp32
  - idf.py build

  - rm -rf build sdkconfig
  - sed -i '$d' sdkconfig.defaults.esp32
  - echo -e "\nCONFIG_APP_BRIDGE_USE_WIFI_PROVISIONING_OVER_BLE=y" >> sdkconfig.defaults.esp32
  - idf.py set-target esp32
  - idf.py build

  - rm -rf build sdkconfig
  - sed -i '$d' sdkconfig.defaults.esp32
  - echo -e "\nCONFIG_BRIDGE_EXTERNAL_NETIF_MODEM=y" >> sdkconfig.defaults.esp32
  - echo -e "\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_ETHERNET=y\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_SPI=y" >> sdkconfig.defaults.esp32
  - idf.py set-target esp32
  - idf.py build

.build_iot_bridge_esp32s2: &build_iot_bridge_esp32s2
  - cd examples/wireless_nic
  - echo -e "\nCONFIG_BRIDGE_EXTERNAL_NETIF_ETHERNET=y" >> sdkconfig.defaults.esp32s2
  - idf.py set-target esp32s2
  - idf.py build

  - rm -rf build sdkconfig
  - sed -i '$d' sdkconfig.defaults.esp32s2
  - echo -e "\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_USB=y" >> sdkconfig.defaults.esp32s2
  - echo -e "\nCONFIG_BRIDGE_EXTERNAL_NETIF_MODEM=y" >> sdkconfig.defaults.esp32s2
  - echo -e "\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_ETHERNET=y\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_SPI=y" >> sdkconfig.defaults.esp32s2
  - idf.py set-target esp32s2
  - idf.py build

.build_iot_bridge_esp32s3: &build_iot_bridge_esp32s3
  - cd examples/wireless_nic
  - echo -e "\nCONFIG_BRIDGE_EXTERNAL_NETIF_ETHERNET=y" >> sdkconfig.defaults.esp32s3
  - idf.py set-target esp32s3
  - idf.py build

  - rm -rf build sdkconfig
  - sed -i '$d' sdkconfig.defaults.esp32s3
  - echo -e "\nCONFIG_APP_BRIDGE_USE_WIFI_PROVISIONING_OVER_BLE=y" >> sdkconfig.defaults.esp32s3
  - idf.py set-target esp32s3
  - idf.py build

  - rm -rf build sdkconfig
  - sed -i '$d' sdkconfig.defaults.esp32s3
  - echo -e "\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_USB=y" >> sdkconfig.defaults.esp32s3
  - echo -e "\nCONFIG_BRIDGE_EXTERNAL_NETIF_MODEM=y" >> sdkconfig.defaults.esp32s3
  - echo -e "\nCONFIG_APP_BRIDGE_USE_WIFI_PROVISIONING_OVER_BLE=y" >> sdkconfig.defaults.esp32s3
  - echo -e "\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_ETHERNET=y\nCONFIG_BRIDGE_DATA_FORWARDING_NETIF_SPI=y" >> sdkconfig.defaults.esp32s3
  - idf.py set-target esp32s3
  - idf.py build

.build_wifi_router_examples: &build_wifi_router_examples
  - cd examples/wifi_router
  - rm -rf build sdkconfig
  - idf.py set-target ${idf_target}
  - idf.py build
  - cd -

.build_wireless_nic_examples: &build_wireless_nic_examples
  - cd examples/wireless_nic
  - rm -rf build sdkconfig
  - idf.py set-target ${idf_target}
  - idf.py build
  - cd -

.build_wired_nic_examples: &build_wired_nic_examples
  - cd examples/wired_nic
  - rm -rf build sdkconfig
  - idf.py set-target ${idf_target}
  - idf.py build
  - cd -

.build_4g_hotspot_examples: &build_4g_hotspot_examples
  - cd examples/4g_hotspot
  - rm -rf build sdkconfig
  - idf.py set-target ${idf_target}
  - idf.py build
  - cd -

.build_4g_nic_examples: &build_4g_nic_examples
  - cd examples/4g_nic
  - rm -rf build sdkconfig
  - idf.py set-target ${idf_target}
  - idf.py build
  - cd -

.build_iot_bridge_examples: &build_iot_bridge_examples
  - *build_wifi_router_examples
  - *build_wireless_nic_examples
  - *build_wired_nic_examples
  - *build_4g_hotspot_examples
  - *build_4g_nic_examples

esp32_v4.3_build:
  stage: build
  image: espressif/idf:release-v4.3
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32
    idf_branch: release/v4.3

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32

esp32_v4.4_build:
  stage: build
  image: espressif/idf:release-v4.4
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32
    idf_branch: release/v4.4

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32

esp32_v5.0_build:
  stage: build
  image: espressif/idf:release-v5.0
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32
    idf_branch: release/v5.0

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32

esp32_v5.1_build:
  stage: build
  image: espressif/idf:release-v5.1
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32
    idf_branch: release/v5.1

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32

esp32c2_v5.0_build:
  stage: build
  image: espressif/idf:release-v5.0
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32c2
    idf_branch: release/v5.0

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_default

esp32c2_v5.1_build:
  stage: build
  image: espressif/idf:release-v5.1
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32c2
    idf_branch: release/v5.1

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_default

esp32c3_v4.3_build:
  stage: build
  image: espressif/idf:release-v4.3
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32c3
    idf_branch: release/v4.3

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_default

esp32c3_v4.4_build:
  stage: build
  image: espressif/idf:release-v4.4
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32c3
    idf_branch: release/v4.4

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_default

esp32c3_v5.0_build:
  stage: build
  image: espressif/idf:release-v5.0
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32c3
    idf_branch: release/v5.0

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_default

esp32c3_v5.1_build:
  stage: build
  image: espressif/idf:release-v5.1
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32c3
    idf_branch: release/v5.1

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_default

esp32s2_v4.4_build:
  stage: build
  image: espressif/idf:release-v4.4
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32s2
    idf_branch: release/v4.4

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32s2

esp32s2_v5.0_build:
  stage: build
  image: espressif/idf:release-v5.0
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32s2
    idf_branch: release/v5.0

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32s2

esp32s2_v5.1_build:
  stage: build
  image: espressif/idf:release-v5.1
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32s2
    idf_branch: release/v5.1

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32s2

esp32s3_v4.4_build:
  stage: build
  image: espressif/idf:release-v4.4
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32s3
    idf_branch: release/v4.4

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32s3

esp32s3_v5.0_build:
  stage: build
  image: espressif/idf:release-v5.0
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32s3
    idf_branch: release/v5.0

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32s3

esp32s3_v5.1_build:
  stage: build
  image: espressif/idf:release-v5.1
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32s3
    idf_branch: release/v5.1

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_esp32s3

esp32c6_v5.1_build:
  stage: build
  image: espressif/idf:release-v5.1
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32c6
    idf_branch: release/v5.1

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_default

esp32h2_v5.1_build:
  stage: build
  image: espressif/idf:release-v5.1
  tags:
    - build

  variables:
    <<: *global-variables
    idf_target: esp32s3
    idf_branch: release/v5.1

  before_script:
    - *before_script_preparation

  script:
    - *setup_esp_idf
    - *build_iot_bridge_examples
    - *build_iot_bridge_default

push_master_to_github:
  stage: deploy
  only:
    - master
#  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
    GITHUB_PUSH_REFS: refs/remotes/origin/release refs/remotes/origin/master
  before_script:
    - echo "skip default before_script"
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - if [ -d "components/iot_bridge/priv_src" ]; then exit 1; fi
    - git remote add github git@github.com:espressif/esp-iot-bridge.git
    - eval $(git for-each-ref --shell bash --format 'if [ $CI_BUILD_REF == %(objectname) ]; then git checkout -B %(refname:strip=3); git push --follow-tags github %(refname:strip=3); fi;' $GITHUB_PUSH_REFS)
